TICK_RATE = 10
NAME_OF_APP = "Help Gendalf"
SCREEN_SIZE = (800, 800)

ADD_CHAR_BUTTON_PLACE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.1)
CHAR_NAME_PLACE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.2)
CHOOSE_CHARACTER_PLACE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.3)
ADD_CORDS_BUTTON_PLACE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.4)
FIRST_COORD_ENTRY_PLACE = (SCREEN_SIZE[0] * 0.2, SCREEN_SIZE[1] * 0.4)
SECOND_COORD_ENTRY_PLACE = (SCREEN_SIZE[0] * 0.3, SCREEN_SIZE[1] * 0.4)


ADD_CHAR_BUTTON_SIZE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.1)
CHAR_NAME_SIZE = (SCREEN_SIZE[0] * 0.2, SCREEN_SIZE[1] * 0.1)
CHOOSE_CHARACTER_SIZE = (SCREEN_SIZE[0] * 0.2, SCREEN_SIZE[1] * 0.1)
ADD_CORDS_BUTTON_SIZE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.1)
FIRST_COORD_ENTRY_SIZE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.1)
SECOND_COORD_ENTRY_SIZE = (SCREEN_SIZE[0] * 0.1, SCREEN_SIZE[1] * 0.1)


SCALE_FOR_DIST_UNIT = 1
CORDS_OF_PIVOT = (SCREEN_SIZE[0] / 2, SCREEN_SIZE[1] / 2)